name: Website CD

on:
  release:
    types:
      - published

env:
  SITE: https://iowarefs.rugby/

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.iowarefs.rugby
          username: deploye@iowarefs.rugby
          password: ${{ secrets.FTP_DEPLOY_PW }}
          local-dir: website/dist
