name: Website CI

on:
  push
  #push:
  #branches:
  #- 'feature/*'
  #- 'main'
  #pull_request:
  #branches:
  #- 'main'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}--node-${{ hashfiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn run website-build

      - name: Test
        run: yarn run website-test
