name: Website CI

on:
  push:
    branches-ignore:
      - 'main'
  workflow-dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Website install
